### ISSUE TITLE
Mispell in dependency name in readme

### ISSUE THREAD

**Issue by tiagonuneslx** [kuuuurt/multiplatform-paging#17]
```
kotlin {
    ...
    sourceSets["commonMain"].dependencies {
        api("io.github.kuuurt:multiplatform-paging:0.4.2")
    }
}
```

kuuurt is spelled here with 3 "u"s instead of 4. This leads to "Could not resolve dependency" error

**Comment by tiagonuneslx** [comment]
Oh just realised there is a pull request for this already (#16)

**Comment by kuuuurt** [comment]
Yikes sorry for the simple mistake and thanks for bringing it to my attention. PR is merged.
