### ISSUE TITLE
Pager tries to mutate a frozen list on iOS

### ISSUE THREAD

**Issue by rickclephas** [kuuuurt/multiplatform-paging#18]
During my investigation of https://github.com/rickclephas/KMP-NativeCoroutines/issues/10 I noticed the `Pager` is [updating](https://github.com/kuuuurt/multiplatform-paging/blob/d9c9a2dcc0d8880bba647728da34db7f048ba52c/paging/src/iosMain/kotlin/com/kuuurt/paging/multiplatform/Pager.kt#L61) the `PagingData` which fails when the pager is frozen.

Since there is already a `StateFlow` I think this could be easily fixed with something like the following:
```kotlin
clientScope.launch {
    val newPagingResult = getItems(key, config.pageSize)
    
    hasNextPage = newPagingResult.items.size >= config.pageSize
    _pagingData.value = PagingData<V>().apply { 
        addAll(_pagingData.value)
        addAll(newPagingResult.items)
    }
    
    currentPagingResult = newPagingResult
}
```

**Comment by kuuuurt** [comment]
Thanks for the report! I have to admit, I haven't been able to check iOS that much. Let me try this out as soon as I free up or since you have a solution already, PRs are also welcome!

**Comment by rickclephas** [comment]
Just tried to apply the changes I proposed but it isn't as easy as I thought.
`currentPagingResult` and `hasNextPage` can't be updated either if the `Pager` is frozen.

**Comment by kuuuurt** [comment]
@rickclephas should be out on v0.4.4
