### ISSUE TITLE
Allow invalidation of paging data

### ISSUE THREAD

**Issue by msfjarvis** [kuuuurt/multiplatform-paging#22]
AndroidX Paging exposes `PagingSource#invalidate` to throw away all currently held state and re-fetch items. 

This is going to be extremely easy to implement for JVM (by deferring to AndroidX), but I'm unsure how to go about it for iOS. If you can provide some tips on that front, I'll be more than happy to send a PR.

**Comment by msfjarvis** [comment]
Hey @kuuuurt would you have a few minutes anytime soon to help me with some tips for this? I'd really appreciate it 🙏

**Comment by kuuuurt** [comment]
Hey @msfjarvis. Sorry about that. I guess for iOS we can just clear the details. Assign null to `pagingData` and `currentPagingResult` then make `hasNextPage` to true.

**Comment by msfjarvis** [comment]
I'm no longer interested in this and it's just sitting in my issue backlog

**Comment by kuuuurt** [comment]
My apologies @msfjarvis as I haven't had the time to work on side projects that much.
