### ISSUE TITLE
1.4.30 support

### ISSUE THREAD

**Issue by joreilly** [kuuuurt/multiplatform-paging#5]
Kotlin 1.4.30 was released a few days ago....not sure if it's binary compatible or not with 1.4.21 but if not be good to get update of this library that supports 1.4.30.

**Comment by kuuuurt** [comment]
@joreilly I've pushed 0.3.3 for the version updates. Sadly, no tests are in place for this lib yet so I haven't tested if everything works as intended but feel free to give it a try. If not, just keep on using 0.3.2
