### ISSUE TITLE
Where's version 0.3.9?

### ISSUE THREAD

**Issue by GuilhE** [kuuuurt/multiplatform-paging#9]
Hi!

Didn't found this version in Jcenter nor MavenCentral 🤔

**Comment by kuuuurt** [comment]
0.3.9 is uploaded in `mavenCentral`

https://search.maven.org/search?q=multiplatform-paging

**Comment by GuilhE** [comment]
Ok, but you've changed the path to
`implementation("io.github.kuuuurt:multiplatform-paging:0.3.9")`

**Comment by kuuuurt** [comment]
Ah, right. I'm sorry about that. Let me update the documentation for that

**Comment by GuilhE** [comment]
No problem ;)
You may also consider removing the Bintray download badge (or replace with the MavenCentral one).
